# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://theunic.github.io
title: Christian Soronellas
subtitle:
author: Christian Soronellas
simple_search: http://google.com/search
description: >
    <p style="text-align:justify">Hi all! My name is Christian Soronellas. I'm a passionate web developer and a software
    craftsman apprentice currently working at <a href="http://emagister.com">Emagister</a> 
    looking forward to learn new things every day. I'm a <strong>PHP 5.3 Zend Certified Engineer</strong>,
    <strong>Zend Framework Certified Engineer</strong> and a <strong>SensioLabs Certified Symfony Developer</strong>.
    I'm also an agile advocate interested in discover new languages and technologies like functional programming (clojure, 
    scala, erlang), javascript, ruby, domain-driven design, test-driven development (TDD), behaviour-driven development (BDD) and so on.</p>

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: theunic@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title.html
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: theUniC
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: theUniC
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: theunic
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-42665670-1

# Facebook Like
facebook_like: false
